from datetime import datetime

from sqlalchemy import Column, Integer, String, Text, DateTime, JSON, Boolean, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship

from ..database import Base


class WikiFolder(Base):
    """A user-created folder for organizing wiki entries. Entries are filed
    into folders manually by the user (see routers/wiki.py's PATCH endpoint)
    - there is no automatic/LLM-driven folder assignment.

    user_id: the wiki is entirely private per account - every folder
    belongs to exactly one User (see app/models/auth.py)."""

    __tablename__ = "wiki_folders"

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    entries = relationship("WikiEntry", back_populates="folder")


class WikiEntry(Base):
    """A long-term-memory knowledge entry, curated wiki-style.

    Entries are created/updated via chat (the update_wiki agent tool), the
    Search panel (web search + a guiding question), the Adjust panel
    (natural-language editing instructions), or by editing the entry
    directly (no LLM involved at all). There is no automatic
    whole-conversation summarization.

    entry_type: which section template this entry follows (see
      app/services/wiki/entry_types.py) when content is (re)generated by the
      LLM - purely about which headings an article gets, unrelated to
      folder organization.
    folder_id: which user-created WikiFolder this entry is filed under
      (nullable - entries with no folder show up as "Uncategorized" in the
      sidebar). Assigned manually by the user, never by the LLM.
    related_titles: a simple "See also" list of other entry titles (plain
      strings, not a graph - there is no knowledge-graph feature).
    created_at: also used to show this entry on the calendar, on whichever
      day it was actually created.
    user_id: the wiki is entirely private per account - every entry belongs
      to exactly one User (see app/models/auth.py). Title is only unique
      *within* an account (see the UniqueConstraint below), not globally -
      two different accounts can each have their own "Python" entry.
    """

    __tablename__ = "wiki_entries"
    __table_args__ = (UniqueConstraint("user_id", "title", name="uq_wiki_entries_user_title"),)

    id = Column(Integer, primary_key=True)
    title = Column(String(255), index=True)
    entry_type = Column(String(50), default="general")
    summary = Column(Text)   # 1-2 sentence summary
    content = Column(Text)   # full Markdown content: lead paragraph + "## Heading" sections
    tags = Column(JSON, default=list)
    related_titles = Column(JSON, default=list)
    is_favorited = Column(Boolean, default=False, index=True)
    folder_id = Column(Integer, ForeignKey("wiki_folders.id"), nullable=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow)

    folder = relationship("WikiFolder", back_populates="entries")
