"""Curated list of OpenAI chat models the user can pick between in the UI's
model switcher/compare panel - restricted to gpt-4o and newer, non-codex
(coding-specialized) models, since this app only needs general-purpose
daily-conversation/summarization quality, not code generation. Pricing/specs
below are OpenAI's published numbers at the time this list was written and
will drift as OpenAI updates them - there's no live pricing API, so this is
maintained by hand.

`recommended` marks the one model shown starred at the top of the picker -
GPT-5.6 Terra, OpenAI's own "balances intelligence and cost" tier of the
current flagship family, which fits everyday chat/summarization better than
the cheaper Luna tier or the pricier reasoning-heavy Sol tier.
"""

MODELS = [
    {
        "id": "gpt-5.6-terra",
        "name": "GPT-5.6 Terra",
        "family": "GPT-5.6",
        "input_price": 2.00,
        "output_price": 12.00,
        "context_window": 1_050_000,
        "knowledge_cutoff": "2026-02-16",
        "blurb": "Balances intelligence and cost - best default for daily conversation and summarization.",
        "recommended": True,
    },
    {
        "id": "gpt-5.6-sol",
        "name": "GPT-5.6 Sol",
        "family": "GPT-5.6",
        "input_price": 5.00,
        "output_price": 30.00,
        "context_window": 1_050_000,
        "knowledge_cutoff": "2026-02-16",
        "blurb": "Frontier model for complex professional work.",
        "recommended": False,
    },
    {
        "id": "gpt-5.6-luna",
        "name": "GPT-5.6 Luna",
        "family": "GPT-5.6",
        "input_price": 0.20,
        "output_price": 1.20,
        "context_window": 1_050_000,
        "knowledge_cutoff": "2026-02-16",
        "blurb": "Optimized for cost-sensitive, high-volume workloads.",
        "recommended": False,
    },
    {
        "id": "gpt-5.5",
        "name": "GPT-5.5",
        "family": "GPT-5.5",
        "input_price": 5.00,
        "output_price": 30.00,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Prior-generation frontier model.",
        "recommended": False,
    },
    {
        "id": "gpt-5.5-pro",
        "name": "GPT-5.5 Pro",
        "family": "GPT-5.5",
        "input_price": 30.00,
        "output_price": 180.00,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Highest-effort reasoning tier of GPT-5.5.",
        "recommended": False,
    },
    {
        "id": "gpt-5.4",
        "name": "GPT-5.4",
        "family": "GPT-5.4",
        "input_price": 2.50,
        "output_price": 15.00,
        "context_window": 1_050_000,
        "knowledge_cutoff": "2025-08-31",
        "blurb": "Prior-generation frontier model.",
        "recommended": False,
    },
    {
        "id": "gpt-5.4-mini",
        "name": "GPT-5.4 Mini",
        "family": "GPT-5.4",
        "input_price": 0.75,
        "output_price": 4.50,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Smaller/cheaper GPT-5.4, still strong for everyday chat.",
        "recommended": False,
    },
    {
        "id": "gpt-5.4-nano",
        "name": "GPT-5.4 Nano",
        "family": "GPT-5.4",
        "input_price": 0.20,
        "output_price": 1.25,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Smallest, fastest GPT-5.4 tier.",
        "recommended": False,
    },
    {
        "id": "gpt-5.4-pro",
        "name": "GPT-5.4 Pro",
        "family": "GPT-5.4",
        "input_price": 30.00,
        "output_price": 180.00,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Highest-effort reasoning tier of GPT-5.4.",
        "recommended": False,
    },
    {
        "id": "gpt-5.3-chat-latest",
        "name": "GPT-5.3 Chat",
        "family": "GPT-5.3",
        "input_price": 1.75,
        "output_price": 14.00,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Conversation-tuned refresh (no extended reasoning step).",
        "recommended": False,
    },
    {
        "id": "gpt-5.2",
        "name": "GPT-5.2",
        "family": "GPT-5.2",
        "input_price": 1.75,
        "output_price": 14.00,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Prior-generation frontier model.",
        "recommended": False,
    },
    {
        "id": "gpt-5.2-chat-latest",
        "name": "GPT-5.2 Chat",
        "family": "GPT-5.2",
        "input_price": 1.75,
        "output_price": 14.00,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Conversation-tuned variant of GPT-5.2.",
        "recommended": False,
    },
    {
        "id": "gpt-5.2-pro",
        "name": "GPT-5.2 Pro",
        "family": "GPT-5.2",
        "input_price": 21.00,
        "output_price": 168.00,
        "context_window": None,
        "knowledge_cutoff": None,
        "blurb": "Highest-effort reasoning tier of GPT-5.2.",
        "recommended": False,
    },
    {
        "id": "gpt-5.1",
        "name": "GPT-5.1",
        "family": "GPT-5.1",
        "input_price": 1.25,
        "output_price": 10.00,
        "context_window": 400_000,
        "knowledge_cutoff": None,
        "blurb": "Prior-generation frontier model.",
        "recommended": False,
    },
    {
        "id": "gpt-5.1-chat-latest",
        "name": "GPT-5.1 Chat",
        "family": "GPT-5.1",
        "input_price": 1.25,
        "output_price": 10.00,
        "context_window": 400_000,
        "knowledge_cutoff": None,
        "blurb": "Conversation-tuned variant of GPT-5.1.",
        "recommended": False,
    },
    {
        "id": "gpt-5",
        "name": "GPT-5",
        "family": "GPT-5",
        "input_price": 1.25,
        "output_price": 10.00,
        "context_window": 400_000,
        "knowledge_cutoff": "2024-09",
        "blurb": "First GPT-5 generation model.",
        "recommended": False,
    },
    {
        "id": "gpt-5-mini",
        "name": "GPT-5 Mini",
        "family": "GPT-5",
        "input_price": 0.25,
        "output_price": 2.00,
        "context_window": 400_000,
        "knowledge_cutoff": "2024-09",
        "blurb": "Smaller/cheaper GPT-5.",
        "recommended": False,
    },
    {
        "id": "gpt-5-nano",
        "name": "GPT-5 Nano",
        "family": "GPT-5",
        "input_price": 0.05,
        "output_price": 0.40,
        "context_window": 400_000,
        "knowledge_cutoff": "2024-09",
        "blurb": "Smallest, fastest GPT-5 tier.",
        "recommended": False,
    },
    {
        "id": "gpt-5-pro",
        "name": "GPT-5 Pro",
        "family": "GPT-5",
        "input_price": 15.00,
        "output_price": 120.00,
        "context_window": 400_000,
        "knowledge_cutoff": "2024-09",
        "blurb": "Highest-effort reasoning tier of GPT-5.",
        "recommended": False,
    },
    {
        "id": "gpt-4.1",
        "name": "GPT-4.1",
        "family": "GPT-4.1",
        "input_price": 2.00,
        "output_price": 8.00,
        "context_window": 1_047_576,
        "knowledge_cutoff": "2024-06",
        "blurb": "Improved-coding, long-context refresh of GPT-4o.",
        "recommended": False,
    },
    {
        "id": "gpt-4.1-mini",
        "name": "GPT-4.1 Mini",
        "family": "GPT-4.1",
        "input_price": 0.40,
        "output_price": 1.60,
        "context_window": 1_047_576,
        "knowledge_cutoff": "2024-06",
        "blurb": "Smaller/cheaper GPT-4.1.",
        "recommended": False,
    },
    {
        "id": "gpt-4.1-nano",
        "name": "GPT-4.1 Nano",
        "family": "GPT-4.1",
        "input_price": 0.10,
        "output_price": 0.40,
        "context_window": 1_047_576,
        "knowledge_cutoff": "2024-06",
        "blurb": "Smallest, fastest GPT-4.1 tier.",
        "recommended": False,
    },
    {
        "id": "gpt-4o",
        "name": "GPT-4o",
        "family": "GPT-4o",
        "input_price": 2.50,
        "output_price": 10.00,
        "context_window": 128_000,
        "knowledge_cutoff": "2023-10",
        "blurb": "Older multimodal flagship - kept for reference/compatibility.",
        "recommended": False,
    },
    {
        "id": "gpt-4o-mini",
        "name": "GPT-4o Mini",
        "family": "GPT-4o",
        "input_price": 0.15,
        "output_price": 0.60,
        "context_window": 128_000,
        "knowledge_cutoff": "2023-10",
        "blurb": "Smaller/cheaper GPT-4o.",
        "recommended": False,
    },
]

_BY_ID = {m["id"]: m for m in MODELS}


def list_models() -> list[dict]:
    """Recommended model first, then the rest in the order defined above
    (newest generation first)."""
    return sorted(MODELS, key=lambda m: not m["recommended"])


def is_valid_model(model_id: str) -> bool:
    return model_id in _BY_ID
